# 1. Secret for Airflow's PostgreSQL Password
apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgres-secret
type: Opaque
data:
  postgres-password: bXlzZWNyZXRwYXNzd29yZA== # mysecretpassword
---
# 2. PVC for Airflow's PostgreSQL Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# 3. PostgreSQL Service for Airflow
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres-service
spec:
  selector:
    app: airflow-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# 4. PostgreSQL Deployment for Airflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgres
  template:
    metadata:
      labels:
        app: airflow-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: "airflow"
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-secret
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: airflow-postgres-pvc
---
# 5. Airflow Scheduler Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: scheduler
        image: puckel/docker-airflow
        args: ["scheduler"]
        env:
        - name: LOAD_EX
          value: "y"
        - name: EXECUTOR
          value: "Local"
        - name: POSTGRES_HOST
          value: "airflow-postgres-service"
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-secret
              key: postgres-password
---
# 6. Airflow Webserver Service
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
spec:
  type: NodePort
  selector:
    app: airflow-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# 7. Airflow Webserver Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - name: webserver
        image: puckel/docker-airflow
        args: ["webserver"]
        ports:
        - containerPort: 8080
        env:
        - name: LOAD_EX
          value: "y"
        - name: EXECUTOR
          value: "Local"
        - name: POSTGRES_HOST
          value: "airflow-postgres-service"
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-postgres-secret
              key: postgres-password