apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  selector:
    name: airflow
  type: NodePort
  ports:
  - name: foo
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: airflow
  labels:
    name: airflow
spec:
  containers:
  - name: airflow
    image: puckel/docker-airflow
    env:
      - name: LOAD_EX
        value: "y"
