apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-health-check
spec:
  schedule: "*/1 * * * *" #	Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: health-checker
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - wget --spider -T 10 http://quakewatch-web
          restartPolicy: OnFailure