apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakewatch-web
  labels:
    app: quakewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quakewatch
  template:
    metadata:
      labels:
        app: quakewatch
    spec:
      containers:
        - name: quakewatch-container
          image: matanreuvental/quakewatch-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort:  5000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name:   API_KEY
              valueFrom:
                secretKeyRef:
                  name: quakewatch-secret
                  key: API_KEY
          envFrom:
            - configMapRef:
                name: quakewatch-config
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
